language: rust
rust:
  - stable
os:
  - linux
  - osx

before_script:
  - rustup target add arm-linux-androideabi
  - rustup target add armv7-linux-androideabi
  - rustup target add aarch64-linux-android
  - rustup target add i686-linux-android

script:
  - cargo check --target=arm-linux-androideabi
  - cargo check --target=arm-linux-androideabi --examples
  - cargo check --target=armv7-linux-androideabi
  - cargo check --target=armv7-linux-androideabi --examples
  - cargo check --target=aarch64-linux-android
  - cargo check --target=aarch64-linux-android --examples
  - cargo check --target=i686-linux-android
  - cargo check --target=i686-linux-android --examples
  - cargo check --target=arm-linux-androideabi --features "bionic-deprecated"
  - cargo check --target=arm-linux-androideabi --examples --features "bionic-deprecated"
  - cargo check --target=armv7-linux-androideabi --features "bionic-deprecated"
  - cargo check --target=armv7-linux-androideabi --examples --features "bionic-deprecated"
  - cargo check --target=aarch64-linux-android --features "bionic-deprecated"
  - cargo check --target=aarch64-linux-android --examples --features "bionic-deprecated"
  - cargo check --target=i686-linux-android --features "bionic-deprecated"
  - cargo check --target=i686-linux-android --examples --features "bionic-deprecated"
  - cargo doc
  - cargo test
